// grab the mongoose module
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var eventSchema = new Schema({
    //id: { type: Number }, // Mongoose has a built in, autogenerated id based on time of creation
    name: {type:String, default: 'New Event'}, // The eventName
    date: { type: Date }, // The built-in mongoose 'Date' includes time, apparently
    location: { type: Schema.ObjectId, ref: 'GPS' }, // Links to a GPS Object ID
    creator: {type: Schema.ObjectId, ref: 'User'}, // Store the creator ID; they're the only one able to edit
    attendees: {type: Array} // Array of UserIDs (people attending the event)
})
// define our event model
// module.exports allows us to pass this to other files when it is called
module.exports = mongoose.model('Event', eventSchema);